### ISSUE TITLE
Server out side of Iran

### ISSUE THREAD

**Issue by v8hid** [WeAreMahsaAmini/FreeInternet#1]
I can provide a server and domain for this project and configuring initial things like DNS, just tell me which linux distro you fell more comfortable with, also suggest a domain.

**Comment by ziXet** [comment]
I can provide servers for testing too.

**Comment by alireza-f** [comment]
> I can provide a server and domain for this project and configuring initial things like DNS, just tell me which linux distro you fell more comfortable with, also suggest a domain.

How can i contact you?

**Comment by v8hid** [comment]
@alireza-f I've added my telegram account on my profile
