### ISSUE TITLE
need help with server setup

### ISSUE THREAD

**Issue by mssayari** [WeAreMahsaAmini/FreeInternet#11]
Hi, 
I've done all the listed steps but I think there is a problem with certs
it's not working and I'm getting this logs on a loop 

```
[Mon Oct  3 13:57:36 UTC 2022] code='200'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:36 UTC 2022] Processing, The CA is processing your order, please just wait. (28/30)
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:36 UTC 2022] sleep 2 secs to verify again
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:38 UTC 2022] checking
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:38 UTC 2022] url='https://acme.zerossl.com/v2/DV90/chall/jvbV0V6IOwhGejLv7zEtvQ'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:38 UTC 2022] payload
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:38 UTC 2022] POST
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:38 UTC 2022] _post_url='https://acme.zerossl.com/v2/DV90/chall/jvbV0V6IOwhGejLv7zEtvQ'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:38 UTC 2022] _CURL='curl --silent --dump-header /acme.sh/http.header  -L '
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:42 UTC 2022] _ret='0'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:42 UTC 2022] code='200'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:42 UTC 2022] Processing, The CA is processing your order, please just wait. (29/30)
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:42 UTC 2022] sleep 2 secs to verify again
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:44 UTC 2022] checking
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:44 UTC 2022] url='https://acme.zerossl.com/v2/DV90/chall/jvbV0V6IOwhGejLv7zEtvQ'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:44 UTC 2022] payload
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:44 UTC 2022] POST
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:44 UTC 2022] _post_url='https://acme.zerossl.com/v2/DV90/chall/jvbV0V6IOwhGejLv7zEtvQ'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:44 UTC 2022] _CURL='curl --silent --dump-header /acme.sh/http.header  -L '
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:47 UTC 2022] _ret='0'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:47 UTC 2022] code='200'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:47 UTC 2022] inima.site:Timeout
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:47 UTC 2022] Skip for removelevel:
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:47 UTC 2022] pid='1196'
shadowsocks-v2ray-tls-acme.sh-1  | [Mon Oct  3 13:57:47 UTC 2022] No need to restore nginx, skip.
```

**Comment by mssayari** [comment]
I managed to run the service and find the problem.

when I activate HTTPS on Arvan, it won't let Zerossl verity the certificate. So we should active it after running docker and starting service then active HTTPS on Arvan.


right now my service is running but couldn't connect with client. I'm still  debugging.

**Comment by mssayari** [comment]
the service is running but I cannot connect to the server. I just disabled the CDN but still can't connect!
do you have any suggestion? 

![image](https://user-images.githubusercontent.com/39558357/193889753-ab0b34c7-d0ca-4372-ba44-8794742606b2.png)

**Comment by Pr0nE** [comment]
Please share your `.env` file and also the config you're using on client, so we can double-check them.

What's your client OS? I personally couldn't connect to my server with windows or mac clients, but the same config works on Android and iOS.

**Comment by mssayari** [comment]
Hi @Pr0nE  thanks for reply. 
This is the `.env`

```
CERT_DIR=/cert
SS_CONTAINER=ss-server
SERVER_PORT=443
METHOD=aes-256-gcm
PASSWORD=forMahsa!

# it needs point to IP of this server
DOMAIN=inima.site

# Feel free to change v2ray path
V2RAY_PATH=simplepath

# debugging

#STAGE=1
DEBUG=1
```

and this is the client config

`ss://YWVzLTI1Ni1nY206Zm9yTWFoc2E@inima.site:443?plugin=v2ray-plugin%3Bpath%3D%2Fsimplepath%3Bhost%3Dinima.site%3Btls`

![image](https://user-images.githubusercontent.com/39558357/193900443-067d02f2-1c58-482a-bb97-693de56cf734.png)

I'm testing on Android. 
btw, I'm not in Iran so I disable the CDN to be able to test directly. I can re-enable the CDN if you need.

I'm on Discord `@Moji` feel free to DM me if you need anything.

**Comment by Pr0nE** [comment]
There's no need for `!` at the end of the pass.
Also, revert `SERVER_PORT` to `4443` as it's not related to the port we specify in the config.
 So your new `.env` would be like below, but your client config would be the same as before:
 ```
 CERT_DIR=/cert
SS_CONTAINER=ss-server
SERVER_PORT=4443
METHOD=aes-256-gcm
PASSWORD=forMahsa

# it needs point to IP of this server
DOMAIN=inima.site

# Feel free to change v2ray path
V2RAY_PATH=simplepath

# debugging

#STAGE=1
DEBUG=1
 ```
 
 After changing .env, clear docker cache and re-build the containers:
 ```
docker-compose down
docker system prune -a
docker-compose build
docker-compose up -d
 ```
 
 btw, having CDN enabled shouldn't cause you any issues, as we've tested it outside of Iran.

**Comment by mssayari** [comment]
Thank you, I think the problem was that port.
I'll send a pull request for credentials.
