### ISSUE TITLE
The server cloud

### ISSUE THREAD

**Issue by mrab72** [WeAreMahsaAmini/FreeInternet#14]
Is there any way to use any other cloud accessible from Iran? Any cloud in Turkey, Dubai, or somewhere else. I really don't wanna use their service when they are one of the most helpful arms of the regime.

**Comment by Pr0nE** [comment]
IMO, it's ok when you're using it against them.
And also the v2ray method only needs a free arvan account, so we're not paying a single rial even.

**Comment by mrab72** [comment]
Anyway, I really want to do something but prefer not to use Arvan. [This](https://www.linkedin.com/in/maryam-abdoli) is my cv; please send a message and let me know if you think I can help with any of the projects. tnx.

**Comment by Pr0nE** [comment]
Appreciate it,
>If you have the technical ability, please check out each protocol Readme file to set up server and open a pull request to share config.
