### ISSUE TITLE
Widnows and Mac clients not working with v2ray method

### ISSUE THREAD

**Issue by Pr0nE** [WeAreMahsaAmini/FreeInternet#19]
Did anyone manage to use the v2ray method on windows or mac clients?

My server config is correct as it works on iOS and Android.

Also, other Shadowsocks configs which do not use the v2ray plugin, work fine for me.

**Comment by payam-zahedi** [comment]
I'm using the Windows client.
You should download the [v2ray ](https://github.com/shadowsocks/v2ray-plugin/releases) plugin for windows, copy it to Shadowsocks folder and rename it to `v2ray-plugin.exe`.


![image](https://user-images.githubusercontent.com/47558577/194832848-bdf9822f-ddb4-44a0-8f44-39cb68e9fa9c.png)

**Comment by payam-zahedi** [comment]
@Pr0nE 
I'm going to add this method to the documentation in my free time.

**Comment by AliAlmasi** [comment]
Also, check this out. A V2Ray client for Windows, support Xray core and v2fly core. [V2rayN](https://github.com/2dust/v2rayN).

**Comment by HamedAhmd** [comment]
I installed the shodowsocks on windows and copied the V2ray into the shadowsocks folder as mentioned here.
But it doesn't change my IP. (The IP is the same, before and after the VPN connection, and VPN doesn't work)

Did anyone have the same problem?

**Comment by Pr0nE** [comment]
> I installed the shodowsocks on windows and copied the V2ray into the shadowsocks folder as mentioned here. But it doesn't change my IP. (The IP is the same, before and after the VPN connection, and VPN doesn't work)
> 
> Did anyone have the same problem?

There are 2 files for windows, try with the other one:
<img width="344" alt="Screen Shot 2022-10-23 at 10 38 53 PM" src="https://user-images.githubusercontent.com/25032492/197411141-7bec7488-1f6b-4cb7-b3b7-ace46cf72986.png">
