### ISSUE TITLE
Where do we keep the ready to use configs?

### ISSUE THREAD

**Issue by ziXet** [WeAreMahsaAmini/FreeInternet#20]
I can set up lots of servers on Azure. I don't have AravanCloud account and cannot create one.
If you have Arvancloud or any other DNS provider in iran, I can send the IP addresses for you to add DNS record to my servers IP addresses.

**Comment by Pr0nE** [comment]
If you're referring to `shadowsocks-v2ray-tls` method, we also need a separate domain for each server to bypass the Intranet with Arvan CDNs.
Btw, if you're outside of Iran, It's possible(and safer) to create Arvan account with an international mobile number.

**Comment by ziXet** [comment]
> If you're referring to `shadowsocks-v2ray-tls` method, we also need a separate domain for each server to bypass the Intranet with Arvan CDNs. Btw, if you're outside of Iran, It's possible(and safer) to create Arvan account with an international mobile number.

Thanks.
It would be great if we can find a domain registrar broker that can donate unfiltered domain names for us to use.
I've registered mine now. waiting for DNS records to propagate.

Is there any private channel for discussions? aside from discord?

**Comment by Pr0nE** [comment]
Anytime,
Actually, I'm not also aware if there is any private space, why do you need one?

btw, we keep our configs [here](https://github.com/WeAreMahsaAmini/FreeInternet/blob/main/guides/shadowsocks-v2ray-tls/CONFIGS.md)

**Comment by ziXet** [comment]
Thanks. you can close this.
