### ISSUE TITLE
Generate shadowsocks url

### ISSUE THREAD

**Issue by sinbolbol** [WeAreMahsaAmini/FreeInternet#23]
I runned the docker files of v2ray method in my cloud server and they are running. But since I'm a beginner, I don't now how to generate an shadowsocks url (the ones looking like ss://.... ) for the clients to connect to. Can anyone help me with this? It would also be a good idea to make the dockers generate the shadowsocks url automatically.

**Comment by Pr0nE** [comment]
Usually, the android and ios clients have an option to export/copy the config you've entered in them.
So first fill config parameters in the client app, check if the config works, then find the export/copy button:

![photo_2022-10-05 14 19 45](https://user-images.githubusercontent.com/25032492/194043889-0cae7c53-5f0b-43d9-81be-46e9a31e77a7.jpeg)

But If you want to create the URL yourself, here is the format:
```
PASSCODE = Base64Encoder(aes-256:PASS)
URL = UrlEncoder(ss://PASSCODE@DOMAIN:443?plugin=v2ray-plugin;path=PATH;host=DOMAIN;tls)
```

https://www.base64decode.org/
https://meyerweb.com/eric/tools/dencoder/

**Comment by CyborgAnderson** [comment]
1. Almost every client software has the function of sharing server node by QR or link, pls try to find in the menu.
2. As the development of different platforms clients are by individual persons, they might not  share same forms of QR or link sometimes, for example the windows desktop [V2rayn](https://github.com/2dust/v2rayN) doesn't share same form with IOS Shadowrocket app, so if you want to share node with others, ask what they use.

**Comment by 0xland** [comment]
https://github.com/WeAreMahsaAmini/FreeInternet/pull/27
