### ISSUE TITLE
Windows terminal traffic 

### ISSUE THREAD

**Issue by payam-zahedi** [WeAreMahsaAmini/FreeInternet#35]
I'm using Windows client app, it works perfectly on browser.
But since this protocol don't work on the terminal and other type of connections.
For example, I can not ping twitter or connect to my GitLab account.

Is there any solution for it?

**Comment by 0xland** [comment]
https://virgool.io/@mmo1362/set-https-proxy-in-windows-command-line-mac-terminal-vufdp6tlymhc
