### ISSUE TITLE
استفاده در لینوکس 

### ISSUE THREAD

**Issue by khodealib** [WeAreMahsaAmini/FreeInternet#41]
از این کانفیگ هایی که گذاشته شده میخواستم بدونم چطور در لینوکس میشه استفاده کرد من در qv2ray خواستم استفاده کنم ولی نشد ارور داد؟

**Comment by 0xland** [comment]
https://github.com/WeAreMahsaAmini/FreeInternet/blob/main/guides/shadowsocks-v2ray-tls/how-to-connect.md#لینوکس
