### ISSUE TITLE
Please add shadowsocks guide for linux

### ISSUE THREAD

**Issue by AlirezaRezaie** [WeAreMahsaAmini/FreeInternet#45]
I tried many VPN and proxies, but I just found Shadowsocks to be working on Android it would be great if you add a tutorial on how to set it up on Linux as well , thanks a lot.

**Comment by 0xland** [comment]
https://github.com/WeAreMahsaAmini/FreeInternet/blob/main/guides/shadowsocks-v2ray-tls/how-to-connect.md#لینوکس
