### ISSUE TITLE
Apple ID locked again

### ISSUE THREAD

**Issue by majid2005** [WeAreMahsaAmini/FreeInternet#49]
Apple id locked and not work

![image](https://user-images.githubusercontent.com/50690279/196049519-49cf2c65-16f8-4260-a5fd-1a135388c57d.jpg)

**Comment by majid2005** [comment]
I want to install it on my dad’s phone but every time i got apple id locked message. Could you please help me ASAP?

**Comment by manizand** [comment]
is there any open source app for iOS ?
it might be possible to distribute it with apple enterprise license...
