### ISSUE TITLE
Mac clients not working

### ISSUE THREAD

**Issue by Rickk137** [WeAreMahsaAmini/FreeInternet#55]
Tried the following methods but none of them works
 - https://github.com/shadowsocks/ShadowsocksX-NG
 - https://github.com/shadowsocks/shadowsocks-libev + https://github.com/shadowsocks/v2ray-plugin
 
 Has anyone been able to set it up on Mac OS?

**Comment by 0xland** [comment]
Not successful with first option, use the command below for second option.

`ss-local -s aiohekl.monster -p 443 -k X8Cecucd2MFmrRXTbBri -m aes-256-gcm -l 1080 --reuse-port --no-delay --plugin v2ray-plugin_darwin_amd64 --plugin-opts 'tls;fast-open;host=aiohekl.monster;path=/redis'`

re-open the issue if you had any further questions.
