### ISSUE TITLE
arvancloud? seriously? 

### ISSUE THREAD

**Issue by alifzl** [WeAreMahsaAmini/FreeInternet#8]
What on earth you propose to use Arvancloud for bypassing Iran's internet censorship? what are you? stupid? 
there are a million other VPS providers in Iran which does not sabotage the user privacy. why did you use the main suspect for this?

**Comment by theStratus** [comment]
Please link them here.

**Comment by alifzl** [comment]
[Server.ir](https://server.ir) , high bandwidth, Pars Online DC
most reliable VPS provider I know [سرودیتا](https://sarvdata.com) 
these ones are surely respect user privacy and their IP ranges are not included in sanctions list yet:
[#1](https://parsdev.com/vps) , [#2](https://saba.host/virtual-server) and [#3](https://blueserver.ir/vps)

**Comment by mssayari** [comment]
As far as I understand, they don't use domestic VPS for this setup, they are just using Arvan's CDN to forward requests to the server.
do we have any other CDN provider in Iran? @alifzl?

**Comment by farnoodma** [comment]
@alifzl If you **actually read** the repo, you'll understand that it suggests using Arvan CDN not their servers. Calling contributors names like "stupid" is not aligned with our cause. Therefore, I'll close this issue.

If you have any constructive suggestions, please feel free to open a PR for it, or create an issue and discuss it. Also, you can join us on Discord and discuss your suggestions on our channel.
